In [1]:
import os
import sys
import pandas as pd
import glob
from PIL import Image
import numpy as np

In [2]:
label_path = '/groups/CS156b/data/student_labels/train2023.csv'
df = pd.read_csv(label_path)
df.head()

,Unnamed: 0.1,Unnamed: 0,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Pneumonia,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,0,0,train/pid50512/study1/view1_frontal.jpg,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,1,train/pid21580/study2/view1_frontal.jpg,Female,87,Frontal,AP,-1.0,NaN,0.0,1.0,NaN,0.0,NaN,1.0,NaN
2,2,2,train/pid21580/study1/view1_frontal.jpg,Female,83,Frontal,AP,-1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN
3,3,3,train/pid21580/study1/view2_lateral.jpg,Female,83,Lateral,NaN,-1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN
4,4,4,train/pid33839/study1/view1_frontal.jpg,Male,41,Frontal,AP,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
matrix = np.array(df.iloc[:, -9:])
means = np.nanmean(matrix, axis=0)
means

array([-0.7346547 , -0.27580503,  0.19076953,  0.83628804,  0.03118294,
        0.3845469 ,  0.52179511,  0.39237415,  0.88828856])

In [4]:
test_df = pd.read_csv('/groups/CS156b/data/student_labels/test_ids.csv')
test_df.head()

   Id                                    Path
0  18  test/pid56785/study1/view1_frontal.jpg
1  19  test/pid56785/study1/view2_lateral.jpg
2  44  test/pid57943/study1/view1_frontal.jpg
3  45  test/pid57943/study2/view1_frontal.jpg
4  57  test/pid54805/study1/view1_frontal.jpg

In [5]:
rows_list = []
for i in range(len(test_df)):
    arr = [test_df['Id'][i]] + list(means)
    rows_list.append(arr)
df_output = pd.DataFrame(rows_list, columns=['Id'] + list(df.columns[-9:]))
df_output.head()

,Id,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Pneumonia,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,18,-0.734655,-0.275805,0.19077,0.836288,0.031183,0.384547,0.521795,0.392374,0.888289
1,19,-0.734655,-0.275805,0.19077,0.836288,0.031183,0.384547,0.521795,0.392374,0.888289
2,44,-0.734655,-0.275805,0.19077,0.836288,0.031183,0.384547,0.521795,0.392374,0.888289
3,45,-0.734655,-0.275805,0.19077,0.836288,0.031183,0.384547,0.521795,0.392374,0.888289
4,57,-0.734655,-0.275805,0.19077,0.836288,0.031183,0.384547,0.521795,0.392374,0.888289

In [6]:
output_dir = '/home/wduan'
full_path = os.path.join(output_dir, 'preds_MSE.csv')
df_output.to_csv(full_path, index=False)